name: "Build"
on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - name: Set-up OCaml 4.14.0
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: 4.14.0
    - run: opam install . --deps-only --with-test
    - run: make
